# Generated by Django 5.1.1 on 2024-09-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_number', models.IntegerField(primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('answers_provided', models.IntegerField(default=0)),
                ('completion_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_number', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('text', 'Text')], max_length=10)),
                ('options', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('points', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('points_earned', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt_app.group')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunt_app.question')),
            ],
        ),
    ]
