# Generated by Django 5.1.1 on 2024-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_location',
            field=models.TextField(default=''),
        ),
    ]
