# Generated by Django 5.1.1 on 2024-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0002_group_group_name_question_question_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='licu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='licu',
            field=models.BooleanField(default=False),
        ),
    ]
