# Generated by Django 5.1.1 on 2024-09-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt_app', '0003_group_licu_question_licu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
